services:
  web:
    build:
      context: ./
      dockerfile: ./apps/admin/Dockerfile
    ports:
      - "8080:80"
  admin:
    build:
      context: ./
      dockerfile: ./apps/web/Dockerfile
    ports:
      - "9080:80"
