name: note build
# 触发workflow的条件
on:
  push:
    # 只有main分支发生push事件时，才会触发workflow
    branches: [test]
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - README.md

jobs:
  build: # 任务的job_id，具体名称自定义，这里build代表打包
    runs-on: ubuntu-latest # runs-on字段指定运行所需要的虚拟机环境。注意：这个是必填字段
    steps:
      - uses: actions/checkout@main
      # 上传打包资源
      - name: Deploy
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.TEST_STARLAND_HOST }}
          user: ${{ secrets.TEST_STARLAND_USERNAME }}
          key: ${{ secrets.TEST_STARLAND_KEY }}
          connect_timeout: 60s
          last_ssh: |
            cd  starland/STARLAND_FRONTEND/
            git checkout .
            git checkout test
            git pull
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            sudo pnpm install
            npm run build:test
            sudo cp -r /home/ubuntu/starland/STARLAND_FRONTEND/apps/admin/dist/* /www/wwwroot/test-admin.star-land.io/dist/
            sudo cp -r /home/ubuntu/starland/STARLAND_FRONTEND/apps/web/dist/*  /www/wwwroot/test.star-land.io/dist/
