name: note build
# 触发workflow的条件
on:
  push:
    # 只有main分支发生push事件时，才会触发workflow
    branches: [test]

jobs:
  build: # 任务的job_id，具体名称自定义，这里build代表打包
    runs-on: ubuntu-latest # runs-on字段指定运行所需要的虚拟机环境。注意：这个是必填字段
    steps:
      - uses: actions/checkout@main
      # 上传打包资源
      - name: Deploy
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.STARLAND_HOST_NAME }}
          user: ${{ secrets.STARLAND_USERNAME }}
          pass: ${{ secrets.STARLAND_PASSWORD }}
          connect_timeout: 60s
          last_ssh: |
            cd ../frontend/TEST/STARLAND_FRONTEND/
            git checkout .
            git checkout test
            git pull
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            pnpm install
            npm run build:test
